name: Node.js CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npm test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Déploiement sur la VM
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: 192.168.1.91
          username: kali
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            mkdir -p /home/${{ secrets.SERVER_USER }}/apps
            cd /home/${{ secrets.SERVER_USER }}/apps

            # Cloner le repo si c'est la première fois
            if [ ! -d "mon-projet" ]; then
              git clone      https://github.com/richard7594/CI-CD2.git  mon-projet
            fi

            cd mon-projet
            git pull origin main
            npm install --production
            pm2 restart app || pm2 start app.js --name app

